# Generated by Django 4.1.1 on 2023-08-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_calendar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
