# Generated by Django 4.1.1 on 2023-08-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='criteria',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
