# Generated by Django 4.1.1 on 2023-08-11 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.response'),
        ),
    ]
