# Generated by Django 4.1.1 on 2023-08-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='response',
        ),
        migrations.AddField(
            model_name='post',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.customer'),
        ),
    ]
