# Generated by Django 4.1.1 on 2023-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_remove_post_response_post_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='criteria',
        ),
        migrations.AddField(
            model_name='post',
            name='criteria',
            field=models.ManyToManyField(to='Blog.task'),
        ),
    ]
