# Generated by Django 4.1.1 on 2023-08-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_remove_post_criteria_post_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='criteria',
        ),
        migrations.AddField(
            model_name='post',
            name='criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.task'),
        ),
    ]
