# Generated by Django 4.1.1 on 2023-08-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='products',
        ),
        migrations.AddField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(to='Blog.product'),
        ),
    ]
