# Generated by Django 4.1.1 on 2023-08-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0017_rename_content_post_evidence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='products',
            new_name='product',
        ),
    ]
