# Generated by Django 4.1.1 on 2023-08-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0021_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='product',
        ),
    ]
