# Generated by Django 4.1.1 on 2023-09-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0031_post_date_alter_post_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='region_name',
        ),
    ]
