# Generated by Django 4.1.1 on 2023-09-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0032_rename_name_region_region_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='region',
            new_name='region_name',
        ),
    ]
