# Generated by Django 4.1.1 on 2023-09-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0034_stripesubscription_mystripemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyStripeModel',
        ),
        migrations.DeleteModel(
            name='StripeSubscription',
        ),
    ]
